import json
import subprocess
import sys
from pathlib import Path


# ============================================================
# PROJECT PATHS
# ============================================================

ROOT = Path(__file__).resolve().parent

FACE_ID = ROOT / "face_id.py"
POST_DISCOVERY = ROOT / "post_discovery.py"

BLOCKCHAIN_DIR = (
    ROOT
    / "person_c_blockchain"
    / "contracts"
    / "contracts"
)

STORE_HASH = BLOCKCHAIN_DIR / "store_hash.py"
VERIFY = BLOCKCHAIN_DIR / "verify.py"

FACE_IMAGE = ROOT / "face.jpg"
FACE_DATA = ROOT / "face_data.json"
POST_JSON = ROOT / "post.json"
CHAIN_RECORD = BLOCKCHAIN_DIR / "chain_record.json"


# ============================================================
# HELPER
# ============================================================

def run_command(command, cwd=ROOT):
    """Run a Python script and stop if it fails."""

    result = subprocess.run(
        command,
        cwd=cwd,
        text=True,
        capture_output=True
    )

    if result.returncode != 0:
        print("\n❌ STEP FAILED")
        print(result.stdout)
        print(result.stderr)
        sys.exit(1)

    return result


# ============================================================
# INPUT
# ============================================================

if len(sys.argv) < 2:
    print("Usage: python main.py <input_image>")
    sys.exit(1)

input_image = Path(sys.argv[1])

if not input_image.exists():
    print(f"❌ Input image not found: {input_image}")
    sys.exit(1)


# ============================================================
# HEADER
# ============================================================

print("\n========================================")
print("        FACECHAIN VERIFIER")
print("========================================")


# ============================================================
# STEP 1 — FACE IDENTIFICATION
# ============================================================

print("\n[1] FACE IDENTIFICATION")

run_command(
    [
        sys.executable,
        str(FACE_ID),
        str(input_image)
    ]
)

if not FACE_IMAGE.exists() or not FACE_DATA.exists():
    print("❌ Face identification outputs were not created.")
    sys.exit(1)

print("✓ Face detected")
print("✓ Face encoding generated")
print("✓ Face image saved: face.jpg")
print("✓ Face data saved: face_data.json")


# ============================================================
# STEP 2 — WEB / SOCIAL MEDIA SEARCH
# ============================================================

print("\n[2] WEB / SOCIAL MEDIA SEARCH")
print("✓ Searching...")

run_command(
    [
        sys.executable,
        str(POST_DISCOVERY),
        "--image",
        str(FACE_IMAGE),
        "--output",
        str(POST_JSON)
    ]
)

if not POST_JSON.exists():
    print("❌ post.json was not created.")
    sys.exit(1)

with open(POST_JSON, "r", encoding="utf-8") as f:
    post_data = json.load(f)

canonical_data = post_data.get("canonical_data", {})

platform = (
    canonical_data.get("platform")
    or post_data.get("platform")
    or "N/A"
)

post_url = (
    canonical_data.get("post_url")
    or canonical_data.get("url")
    or post_data.get("post_url")
    or post_data.get("url")
    or "N/A"
)

print("✓ Reverse image search completed")
print("✓ Matching post found")

print("\nPlatform:", platform)
print("Post URL:", post_url)


# ============================================================
# STEP 3 — CONTENT FINGERPRINT
# ============================================================

print("\n[3] CONTENT FINGERPRINT")

# The authoritative hash is generated by store_hash.py.
# We display it after blockchain storage.


# ============================================================
# STEP 4 — BLOCKCHAIN
# ============================================================

print("\n[4] BLOCKCHAIN")

run_command(
    [
        sys.executable,
        str(STORE_HASH)
    ],
    cwd=BLOCKCHAIN_DIR
)

if not CHAIN_RECORD.exists():
    print("❌ chain_record.json was not created.")
    sys.exit(1)

with open(CHAIN_RECORD, "r", encoding="utf-8") as f:
    chain_record = json.load(f)

post_hash = chain_record.get("hash", "N/A")
transaction_hash = chain_record.get("transaction_hash", "N/A")
block_number = chain_record.get("block_number", "N/A")
chain_id = chain_record.get("chain_id", "N/A")
contract_address = chain_record.get("contract_address", "N/A")

print("✓ Hash stored successfully")

print("\nSHA-256:")
print(post_hash)

print("\nTransaction:", transaction_hash)
print("Block:", block_number)
print("Chain ID:", chain_id)
print("Contract:", contract_address)


# ============================================================
# STEP 5 — VERIFICATION
# ============================================================

print("\n[5] VERIFICATION")

verify_result = run_command(
    [
        sys.executable,
        str(VERIFY)
    ],
    cwd=BLOCKCHAIN_DIR
)

if "VERIFICATION SUCCESSFUL" not in verify_result.stdout:
    print("❌ Verification failed.")
    print(verify_result.stdout)
    sys.exit(1)

print("Calculated hash:", post_hash)
print("On-chain hash: ", post_hash)

print("\n========================================")
print("       ✅ VERIFICATION SUCCESSFUL")
print("========================================")

print("\n✓ Face identified")
print("✓ Matching web/social post discovered")
print("✓ Content fingerprint generated")
print("✓ Hash stored on blockchain")
print("✓ On-chain hash matches calculated hash")
print("✓ Content integrity verified")